### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TamaraAtanasoska** [Heidelberg-NLP/amr-argument-sim#1]
Both this repository and the [suite repository](https://github.com/Heidelberg-NLP/amr-argument-sim) don't have a license attached. I am working on a project as part of a University course that is aiming to reproduce the paper where this metric is introduced, and possibly extend it. 
For that, I have cloned both repositories locally and I would want to host them here [in my own repository](https://github.com/TamaraAtanasoska/AMR_ArgumentSimilarity), which will be clearly attributed and marked as reproduction with links back to the originals. The cleanest solution would be to remove the .git folders from each repository and upload the blobs of code as such to be connected with one global .git history. 
Without an explicit license I don't feel comfortable doing this. I will push the local state to a [branch](https://github.com/TamaraAtanasoska/AMR_ArgumentSimilarity/tree/repro_repos) and I hope to hear from you in the meantime. I will also bring this up in a meeting with the designated professor tomorrow. 

Thank you!

**Comment by flipz357** [comment]
Added license
